### ISSUE TITLE
puzzled how to prepare the input data for model

### ISSUE THREAD

**Issue by dingxinjun** [iiasa/CWatM#10]
Thank you Professor Peter Burek and your iiasa water program group share 5 CWATM_exercise on github and patiently design the guideline for master CWATM model. when i'm learning this model. i can excetute the command line to run the rhine demo. when i want to apply the model th a specific basin, i know the input file should have the data structure and folder structure like demo.But the material inside the folder and it's format puzzled me. so i hope your team canhave a youtube channel to share how to prepare the input data from 0 to1. especially some data set have low resolution can we use interpolate method for high resolution demand.

**Comment by mikhailsmilovic** [comment]
Guten Tag, we have started creating YouTube tutorials to run the model; thank you for the suggestion! 
https://www.youtube.com/playlist?list=PLyT8dd_rWLaymQIewMyzVcjMYvPR8Rqtw

We are currently creating tutorials for running the model with the global 30-arcminute (and soon 5-arcminute) dataset and comparing with observations from Google Earth Engine and GRDC River discharge stations. We will soon get to tailoring some of the inputs.

**Comment by dingxinjun** [comment]
Thank you, Professor! I have followed your channel. Thank you for creating detailed and patient videos, guiding us step by step on how to operate the model.

**Comment by mikhailsmilovic** [comment]
My pleasure; glad the videos are helpful. 
Thank you for the awesome feedback!
