### ISSUE TITLE
CWatM model simulation can be set to multi-process and speed up the simulation? 

### ISSUE THREAD

**Issue by Defeng-Wu** [iiasa/CWatM#40]
### Discussed in https://github.com/iiasa/CWatM/discussions/9

<div type='discussions-op-text'>

<sup>Originally posted by **Zhyu-1** December 12, 2020</sup>
Hi Mikhail and everyone,
My name is Defeng Wu, I am a PhD candidate with China Agricultural University (CAU). I have been learning the CWatM model for half a year and it looks great. 
Now，I can  simulate the hydrological process of the whole China from 1979 to 2018, but it takes almost one and a half hours to run for a year. CWatM model simulation can be set to multi-process and speed up the simulation? Can you help and tell me how to speed up the simulation?</div>

**Comment by mikhailsmilovic** [comment]
Guten Tag Defeng!
Awesome to hear about the China model 🌏 For a China model at 5 arcminutes (~10 km), this is ~960,000 cells.
The settings **NoRoutingSteps** is the number of sub-daily steps and can be reduced for faster runs, especially for setting up and testing. 

Loose recommendations: 
At 30 arcminutes, NoRoutingSteps = 10
At 5 arcminutes, NoRoutingSteps = 24

Sub-daily steps are used in the modules for routing, soil, and lakes & reservoirs. 
Let us assume water with a speed of ~1 m/s = ~86.4 km/day. At ~10km resolution, discharge leaving a cell needs ~8 substeps to reach a cell ~86.4 km away (say, 8 cells away). At ~1 m/s with 24 substeps, at least 66% of the water leaving cells has the "substep time" to reach cells 8 cells away. 

Reducing the number of routing steps may mean capturing the high flows less well. It can be interesting to test different NoRoutingSteps for a wetter period in your model.

For multi-processing, many parts of the model depend on previous modules. For calibration, we use a tool that runs several setups of the model in parallel.

**Comment by Defeng-Wu** [comment]
Thank you very much for this helpful details. Then i will try, and look forward to the good news.
